[package]
name = "ublox-proto"
version = "0.1.0"
authors = ["Martin Hundebøll <martin@geanix.com>", "Tue Henriksen <tue.henriksen@r2p.com>"]
edition = "2018"

[dependencies]
log = "0.4"
num_enum = "0.5"
